metadata:
  name: github-enterprise-disable-dependabot
  version: 2.0.0
  description: The following analytic detects when a user disables Dependabot security
    features within a GitHub repository. Dependabot helps automatically identify and
    fix security vulnerabilities in dependencies. The detection monitors GitHub Enterprise
    logs for configuration changes that disable Dependabot functionality. This behavior
    could indicate an attacker attempting to prevent the automatic detection of vulnerable
    dependencies, which would allow them to exploit known vulnerabilities that would
    otherwis
  author: Patrick Bareiss, Splunk
  tags:
  - anomaly
  - splunk-security-content
  - github-malicious-activity
  mitre_attack:
    techniques:
    - id: T1562.001
      name: Technique T1562.001
    - id: T1195
      name: Technique T1195
    tactics: []
files:
  bundled: []
  references:
  - uri: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562.001/disable_dependabot/github.json
    description: http:github - httpevent
    format: jsonl
    schema: raw
defaults:
  replay:
    delta_factor: 1.0
    base_time: earliest
    target_time: now-1h
  schema: raw
